// =============================================================================
// softmax_unit_tb.sv  —  Accuracy testbench
// Generates N_ROWS random input rows, drives the DUT, captures outputs,
// and writes everything to a text file for Python to evaluate.
//
// Output file format (one line per row):
//   INPUT:  v0 v1 v2 ... v15        (signed decimal Q8.8 integers)
//   OUTPUT: o0 o1 o2 ... o15        (unsigned decimal uint8)
//
// Run from Vivado TCL:
//   launch_simulation
//   run 5ms
//
// Then run:
//   python rtl_accuracy.py
// =============================================================================
`timescale 1ns / 1ps

module softmax_unit_tb;

    import softmax_pkg::*;

    // ── Clock & reset ────────────────────────────────────────────────────────
    logic clk = 0;
    always #5 clk = ~clk;   // 100 MHz

    logic rst_n = 0;

    // ── DUT ports ────────────────────────────────────────────────────────────
    logic                          in_valid = 0;
    logic                          in_first = 0;
    logic signed [DATA_WIDTH-1:0]  in_data  = 0;
    logic                          out_valid;
    logic [OUT_WIDTH-1:0]          out_data;
    logic                          busy;

    softmax_unit dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .in_valid (in_valid),
        .in_first (in_first),
        .in_data  (in_data),
        .out_valid(out_valid),
        .out_data (out_data),
        .busy     (busy)
    );

    // ── Parameters ───────────────────────────────────────────────────────────
    localparam int N_ROWS   = 500;      // number of random rows to test
    localparam int SEED     = 42;       // not used directly — rows pre-generated
    localparam string OUT_FILE = "C:/Users/IsaiahK/Documents/School/FPGA/transformer/softmax/sim/rtl_outputs.txt";

    // ── Storage ──────────────────────────────────────────────────────────────
    logic signed [DATA_WIDTH-1:0] input_rows  [0:N_ROWS-1][0:SEQ_LEN-1];
    logic        [OUT_WIDTH-1:0]  output_rows [0:N_ROWS-1][0:SEQ_LEN-1];

    integer fd_in;   // file handle for reading inputs
    integer fd_out;  // file handle for writing outputs
    integer r;

    // ── Tasks ─────────────────────────────────────────────────────────────────

    // Send one row to the DUT, one token per clock
    task automatic send_row(input int row_idx);
        for (int i = 0; i < SEQ_LEN; i++) begin
            @(posedge clk);
            in_valid <= 1'b1;
            in_first <= (i == 0) ? 1'b1 : 1'b0;
            in_data  <= input_rows[row_idx][i];
        end
        @(posedge clk);
        in_valid <= 1'b0;
        in_first <= 1'b0;
    endtask

    // Capture one row of output from the DUT
    task automatic capture_row(input int row_idx);
        int cap_cnt;
        cap_cnt = 0;
        // Wait for out_valid to go high
        while (!out_valid) @(posedge clk);
        // Capture SEQ_LEN values
        while (cap_cnt < SEQ_LEN) begin
            if (out_valid) begin
                output_rows[row_idx][cap_cnt] <= out_data;
                cap_cnt++;
            end
            @(posedge clk);
        end
    endtask

    // ── Main stimulus ─────────────────────────────────────────────────────────
    initial begin
        // ── Reset ────────────────────────────────────────────────────────────
        rst_n = 0;
        repeat(4) @(posedge clk);
        rst_n = 1;
        repeat(2) @(posedge clk);

        // ── Load input rows from file ─────────────────────────────────────────
        // The file is generated by rtl_accuracy.py --gen-inputs
        // Format: one row per line, SEQ_LEN signed integers space-separated
        fd_in = $fopen("C:/Users/IsaiahK/Documents/School/FPGA/transformer/softmax/sim/rtl_inputs.txt", "r");
        if (fd_in == 0) begin
            $display("ERROR: could not open rtl_inputs.txt");
            $display("Run: python rtl_accuracy.py --gen-inputs  first");
            $finish;
        end

        for (int row = 0; row < N_ROWS; row++) begin
            for (int i = 0; i < SEQ_LEN; i++) begin
                r = $fscanf(fd_in, "%d", input_rows[row][i]);
            end
        end
        $fclose(fd_in);
        $display("[tb] Loaded %0d input rows", N_ROWS);

        // ── Run DUT on each row ───────────────────────────────────────────────
        for (int row = 0; row < N_ROWS; row++) begin
            fork
                send_row(row);
                capture_row(row);
            join
            // Small gap between rows
            repeat(2) @(posedge clk);

            if (row % 50 == 0)
                $display("[tb] Completed row %0d / %0d", row, N_ROWS);
        end

        // ── Write outputs to file ─────────────────────────────────────────────
        fd_out = $fopen(OUT_FILE, "w");
        if (fd_out == 0) begin
            $display("ERROR: could not open output file %s", OUT_FILE);
            $finish;
        end

        for (int row = 0; row < N_ROWS; row++) begin
            // Write input row
            $fwrite(fd_out, "INPUT:");
            for (int i = 0; i < SEQ_LEN; i++)
                $fwrite(fd_out, " %0d", input_rows[row][i]);
            $fwrite(fd_out, "\n");

            // Write output row
            $fwrite(fd_out, "OUTPUT:");
            for (int i = 0; i < SEQ_LEN; i++)
                $fwrite(fd_out, " %0d", output_rows[row][i]);
            $fwrite(fd_out, "\n");
        end

        $fclose(fd_out);
        $display("[tb] Wrote outputs to %s", OUT_FILE);
        $display("[tb] Done. Run: python rtl_accuracy.py");
        $finish;
    end

endmodule
